version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=bufo@hweeks.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.bufooffers.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$hXGPoJ3$$97uBIMAXeeObWcli2X9i1."

  app:
    image: ghcr.io/hweeks/bufo-offers-gen:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`bufooffers.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.app-https.rule=Host(`bufooffers.com`)"
      - "traefik.http.routers.app-https.entrypoints=web"
      - "traefik.http.routers.app-https.middlewares=redirect-to-https"
    ports:
      - "3005:3005"
    networks:
      - web

networks:
  web:
    external: true
